# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ec503ff6687265af2f8bad8884e428e50d5a7a0027da188897dc7b1e0ae41bd3a045116ec7857390e6992eeb543d169b35bbf9cd651522dea66d56c57cdc6b80

test:
  secret_key_base: 4c0c72844bcd8fa366ef8bdb8957e158e9013af90f71e1350397b53500b2539dcf68b97e46b44be3da0cc1a4f86ae2c9a6635744c40ba5521de9d15467e7adb8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
